title: Piedmont Makers Club FLL Challenge Team (NEED A NAME!)
description: A simple website with blog and photos
url: "https://fll.sharpers.com"
baseurl: ""

# Development overrides (use with: bundle exec jekyll serve --config _config.yml,_config_dev.yml)
# For local development, baseurl should be "/fll"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Disable default theme
theme:

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor